const MAX_OUTPUT_IMAGE_DIMENSION = 3000;
const MAX_OUTPUT_JPEG_IMAGE_DIMENSION = 5000;
const NOT_PROCESSED_EXTENSIONS = ["svg", "gif"];
const DEFAULT_PARAMS = ["format/auto", "stretch/off", "progressive/yes"];
const DEFAULT_CDN_DOMAIN = 'ucarecdn.com';

module.exports = {
  MAX_OUTPUT_IMAGE_DIMENSION,
  MAX_OUTPUT_JPEG_IMAGE_DIMENSION,
  NOT_PROCESSED_EXTENSIONS,
  DEFAULT_PARAMS,
  DEFAULT_CDN_DOMAIN
}
